chore: merge 시 UNDO ICON 에러 해결
devBuzz142/numanku-fe pull request #15
Opened 2023-11-07 01:58 UTC by jeehyojeon

제가 merge할 때 잘 못 봐서 에러 생겼는데 해결했습니다ㅠㅠ
지금 dev로 pull 받으면 에러나요

2023-11-07 06:13 UTC, devBuzz142 requested changes

2023-11-07 06:13 UTC, devBuzz142 commented on src/pages/ViewCompletePage/ViewCompletePage.jsx
> +      </Routes>
라우트 컴포넌트에 대해 잘못 이해하신 것 같습니다. react-router 문서를 다시 확인해보시는 것을 추천드립니다.

2023-11-07 06:13 UTC, devBuzz142 commented on src/pages/ViewCompletePage/ViewCompletePage.jsx
> +      setRedirectToView(true);
5초 후에 상태변경이 아니라 바로
```
navigate(url)
```
을 통해서 /view로 보내주는게 어떤가 합니다!

2023-11-07 06:53 UTC, jeehyojeon commented on src/pages/ViewCompletePage/ViewCompletePage.jsx
> +      </Routes>
넵 다시 확인해보겠습니다!! 감사합니다!

2023-11-07 16:11 UTC, devBuzz142 approved these changes
textarea만 수정하시면 될 것 같습니다!

2023-11-07 16:11 UTC, devBuzz142 commented on src/components/Input/Input.style.jsx
> +export const Textarea = styled.input`
styled.input이면 input element입니다.
textarea element를 사용하려면 styled.textarea를 해주셔야합니다.

2023-11-07 16:16 UTC, devBuzz142 approved these changes

2023-11-07 16:16 UTC, devBuzz142 commented on src/components/Input/Input.jsx
>            placeholder={placeholder}
밑에 type === Textarea인 경우를 더 자세하게 작성하신 것으로 봐선 그쪽을 쓰시는 것 같은데 그렇다면 이 부분은 필요 없을 것 같습니다.
코드 흐름상 if id === KukiContents를 검사하고 맞을 경우 바로 return하기 때문에
아래에 있는 if type === Textarea로는 안 내려가겠습니다.

2023-11-07 16:16 UTC, devBuzz142 commented on src/components/Input/Input.jsx
> +  if (type === "Textarea") {
다른 부분과 컨벤션 맞춰서 textarea로 가면 좋을 듯 합니다.

2023-11-07 16:16 UTC, devBuzz142 commented on src/components/Input/Input.style.jsx
> +export const Textarea = styled.input`
input이 아니라 textarea로 하셔야합니다. 서로 다른 엘리먼트입니다.

2023-11-09 17:32 UTC, jeehyojeon commented on src/components/Input/Input.jsx
>            placeholder={placeholder}
헉 순서를 생각 못했네요 감사합니다!!!

2023-11-11 07:46 UTC, merged